title: Dark MS Theme
description: Dark MS Theme is a clean, responsive theme for GitHub Pages.
#show_downloads: false
#hide_github: true
favicon: https://webiconspng.com/wp-content/uploads/2017/09/Microsoft-PNG-Image-83610.png
buttons:
  - text: Test Header Button
    href: http://example.net
  - text: Cheese Goblin
    href: http://google.com