title: Dark MS Theme
description: A simple GitHub Pages theme with Microsoft fonts & colours
#show_downloads: false
#hide_github: true
favicon: https://webiconspng.com/wp-content/uploads/2017/09/Microsoft-PNG-Image-83610.png
buttons:
  - text: Test Header Button
    href: http://example.net
