title: Dark MS Theme
description: Dark MS Theme is a clean, responsive theme for GitHub Pages.
show_downloads: false
hide_github: true
favicon: http://nodejs-cloud.com/img/128px/nodejs.png
buttons:
  - b1:
    text: Test Header Button
    href: http://example.net